name: SonarCloud

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # or '11' based on your project
          distribution: 'temurin'  # Ensure this is correct

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make Gradlew executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        with:
          projectBaseDir: '.'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SECURITY_TOKEN }}

